# Generated by Django 4.2.7 on 2023-11-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_alter_subscription_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subsciptions',
            new_name='subscriptions',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_to', to='insta.profile'),
        ),
    ]
