# Generated by Django 4.2.7 on 2023-11-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_rename_subsciptions_profile_subscriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.BigIntegerField(default=0),
        ),
    ]
