# Generated by Django 4.2.7 on 2023-11-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_alter_profile_user_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_moments',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_subscribers',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_subscriptions',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
