# Generated by Django 4.2.7 on 2023-11-14 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_profile_number_of_moments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='moment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='insta.moment'),
        ),
    ]
