# Generated by Django 4.2.7 on 2023-11-14 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_alter_comment_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='moment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='insta.moment'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='insta.profile'),
        ),
    ]
