# Generated by Django 4.2.7 on 2023-11-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_alter_comment_moment_alter_moment_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('author', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='momentlike',
            unique_together={('author', 'moment')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('author', 'subscriber')},
        ),
    ]
