# Generated by Django 4.2.7 on 2023-12-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0012_comment_liked_by_moment_liked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='moment',
            name='liked_by',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.profile'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='insta.profile'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='insta.comment'),
        ),
        migrations.AlterField(
            model_name='momentlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_likes', to='insta.profile'),
        ),
        migrations.AlterField(
            model_name='momentlike',
            name='moment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_likes', to='insta.moment'),
        ),
    ]
