# Generated by Django 4.2.7 on 2023-12-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0015_alter_commentlike_author_alter_commentlike_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_likes_by', to='insta.profile'),
        ),
    ]
