# Generated by Django 4.2.7 on 2023-12-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0016_alter_momentlike_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='liked_by',
            field=models.ManyToManyField(through='insta.MomentLike', to='insta.profile'),
        ),
    ]
