# Generated by Django 4.2.7 on 2023-12-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0017_moment_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='liked_by',
        ),
    ]
